[tool.kedro]
package_name = "projet_ml_ops"
project_name = "projet_ml_ops"
project_version = "0.17.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/projet_ml_ops -ra"""
